# Generated by Django 4.1.2 on 2022-10-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(["rental", "checkin"], name="rental_checkin_idx"),
        ),
    ]
